[package]
name = "rust_asteroids"
version = "0.1.0"
authors = ["vjrao, rphmeier <rphmeier@gmail.com>"]

[dependencies]
<<<<<<< HEAD
glium = "^0.13"
glutin = "^0.4"
jobsteal = "^0.2"
rand = "^0.3"
time = "0.1"

[dependencies.engine]
git = "https://github.com/rphmeier/rust_toy_engine.git"